### ISSUE TITLE
Great Resource worth using - Are these available for DNA nexus platform?

### ISSUE THREAD

**Issue by akhilpampana** [atgu/hgdp_tgp#5]
Hello, 

I appreciate your wonderful tutorial and paper so much. Congratulations on your work; it is an excellent resource for the research community.

I have a question for you.
1. Is it possible to download these data sources from AWS? In that case, could you help with the links?

I sincerely appreciate your help, and I look forward to speaking with you soon.

Regards
Akhil

**Comment by akhilpampana** [comment]
Hello,

I am also trying to check the tutorial dataset to copy the files to my bucket but I am getting errors as mentioned below. 

![image](https://user-images.githubusercontent.com/19439352/215632943-5b2eda69-165c-4cbb-84d1-52c6d3b13c25.png)

Please do let me know how to proceed from here.

Regards
Akhil

**Comment by z-koenig** [comment]
The data for the tutorials will be available from google cloud, and at this time we will not be hosting the data on AWS. 

We are currently in the process of pushing our last changes and moving our data to a gcloud public bucket so in the meantime the data from the tutorials is unavailable. The current paths in our tutorial scripts are not the final paths for the data. We will be updating the scripts and readme with the final dataset paths once they are moved. 

Thank you for your inquiry, and we appreciate your patience as we complete these last steps in our tutorial rollout. 

If you have any additional questions in the meantime, please let us know.

**Comment by akhilpampana** [comment]
Hello, 

Thank you so much for the clarification, and I am excited to use the resources available. I would like to ask you a follow-up question, is the tgp_hgdp intersection dataset the same dataset that was used in the pan-UK biobank analysis? Do you have any idea regarding that? I understand these are two different projects, but I thought of asking you.

Regardless, thank you so much for your response, and I look forward to the resource. 

Akhil

**Comment by z-koenig** [comment]
Yes that is correct. 

As mentioned in our preprint, our resource has been used in the Pan-UK Biobank project.

**Comment by akhilpampana** [comment]
Great, thank you so much. I was trying to replicate ancestry assignments that were done in pan ukbiobank so thought of asking. 
Thank you so much for your help. I will close this issue and look forward to your great resource access.
