### ISSUE TITLE
is it possible to assign ancestry for precomputed pcs without access to genetic dataset?

### ISSUE THREAD

**Issue by akhilpampana** [atgu/hgdp_tgp#8]
Hello,

I have principal components provided by the dataset and have pcs from HGDP and 1000g dataset with superpopulation information available. Can I assign the ancestry if this is the case?

Thank you so much for the help?

Regards
Akhil

**Comment by z-koenig** [comment]
I don't know if I fully understand what you are asking, but you are able to run your own analyses and assign ancestry labels, if that is what you are looking to do. Information on how to do that is in notebook 5 of our tutorials.

**Comment by akhilpampana** [comment]
I am sorry for the confusion in the question. I believe I got my answer. Thank you so much for the response
